development:
  adapter: mysql2
  encoding: utf8
  database: click_my_social_development
  pool: 5
  username: root
  password:
  socket: /var/run/mysqld/mysqld.sock

production:
  adapter: mysql2
  encoding: utf8
  database: click_my_social
  pool: 5
  username: root
  password:
  socket: /var/run/mysqld/mysqld.sock
